def dw1(driverliste):

    for i in range(len(driverliste)):
        driver = driverliste[i]
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        switch(1,driver)
        ok(driver)
        Gebäude(1,driver)
        ok(driver)
        verschicken(1,3,['w'],['2640'],driver)
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        Gebäude(1,driver)
        ok(driver)
        verschicken(1,4,['w'],['2640'],driver)
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        Gebäude(1,driver)
        ok(driver)
        verschicken(1,5,['w'],['2640'],driver)
        ok(driver)
        ansicht('s',driver)
        ok(driver)

def ww1(driverliste):

    for i in range(len(driverliste)):
        driver = driverliste[i]
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        switch(1,driver)
        ok(driver)
        Gebäude(1,driver)
        ok(driver)
        verschicken(1,3,['w'],['18480'],driver)
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        Gebäude(1,driver)
        ok(driver)
        verschicken(1,4,['w'],['18480'],driver)
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        Gebäude(1,driver)
        ok(driver)
        verschicken(1,5,['w'],['18480'],driver)
        ok(driver)
        ansicht('s',driver)
        ok(driver)

def m1(anzahl,driverliste):

    for i in range(len(driverliste)):
        driver = driverliste[i]
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        switch(3,driver)
        ok(driver)
        Gebäude(1,driver)
        ok(driver)
        verschicken(3,1,['m'],[anzahl],driver)
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        Gebäude(1,driver)
        ok(driver)
        verschicken(3,2,['m'],[anzahl],driver)
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        Gebäude(1,driver)
        ok(driver)
        verschicken(3,4,['m'],[anzahl],driver)
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        Gebäude(1,driver)
        ok(driver)
        verschicken(3,5,['m'],[anzahl],driver)
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        
def ver(von,nach,Typ,anzah,driverliste):

    for i in range(len(driverliste)):
        driver = driverliste[i]
        ok(driver)
        ansicht('s',driver)
        ok(driver)
        switch(von,driver)
        ok(driver)
        Gebäude(1,driver)
        ok(driver)
        verschicken(von,nach,Typ,anzah,driver)
        ok(driver)
        ansicht('s',driver)
        ok(driver)
